"""Repository for persisting and querying student and role skill vectors in pgvector.

Enforces strict model isolation: vectors generated by different models are never compared.
"""

from typing import Any, Dict, List, Optional
import math
from app.services.embedding_service import EMBEDDING_MODEL_NAME, EXPECTED_EMBEDDING_DIM


class ModelMismatchError(ValueError):
    """Raised when comparing or searching across vectors from different models."""
    pass


class VectorRepository:
    """Repository handling pgvector storage and similarity searches."""

    def __init__(self, db_pool: Any = None):
        self.db_pool = db_pool
        # In-memory storage for testing or offline mode
        self._student_vectors: Dict[str, Dict[str, Any]] = {}
        self._role_vectors: Dict[str, Dict[str, Any]] = {}

    async def save_student_profile_vector(
        self,
        student_id: str,
        profile_text: str,
        embedding: List[float],
        embedding_model: str = EMBEDDING_MODEL_NAME
    ) -> Dict[str, Any]:
        """Persist a student profile vector along with the embedding model name."""
        if not embedding_model:
            raise ValueError("embedding_model cannot be empty.")
        if len(embedding) != EXPECTED_EMBEDDING_DIM:
            raise ValueError(f"Vector dimension must be {EXPECTED_EMBEDDING_DIM}, got {len(embedding)}")

        record = {
            "student_id": student_id,
            "profile_text": profile_text,
            "embedding": embedding,
            "embedding_model": embedding_model,
        }

        if self.db_pool:
            query = """
                INSERT INTO public.student_profile_vectors (
                    student_id, profile_text, embedding, embedding_model, updated_at
                ) VALUES ($1, $2, $3, $4, NOW())
                ON CONFLICT (student_id, embedding_model) DO UPDATE SET
                    profile_text = EXCLUDED.profile_text,
                    embedding = EXCLUDED.embedding,
                    updated_at = NOW()
                RETURNING *;
            """
            # If using asyncpg db_pool:
            result = await self.db_pool.fetchrow(
                query, student_id, profile_text, str(embedding), embedding_model
            )
            return dict(result) if result else record

        # Fallback / In-Memory persistence
        key = f"{student_id}::{embedding_model}"
        self._student_vectors[key] = record
        return record

    async def save_role_requirement_vector(
        self,
        role_id: str,
        role_title: str,
        requirements_text: str,
        embedding: List[float],
        embedding_model: str = EMBEDDING_MODEL_NAME
    ) -> Dict[str, Any]:
        """Persist a role requirement vector along with the embedding model name."""
        if not embedding_model:
            raise ValueError("embedding_model cannot be empty.")
        if len(embedding) != EXPECTED_EMBEDDING_DIM:
            raise ValueError(f"Vector dimension must be {EXPECTED_EMBEDDING_DIM}, got {len(embedding)}")

        record = {
            "role_id": role_id,
            "role_title": role_title,
            "requirements_text": requirements_text,
            "embedding": embedding,
            "embedding_model": embedding_model,
        }

        if self.db_pool:
            query = """
                INSERT INTO public.role_requirements (
                    role_id, role_title, requirements_text, embedding, embedding_model, updated_at
                ) VALUES ($1, $2, $3, $4, NOW())
                ON CONFLICT (role_id, embedding_model) DO UPDATE SET
                    role_title = EXCLUDED.role_title,
                    requirements_text = EXCLUDED.requirements_text,
                    embedding = EXCLUDED.embedding,
                    updated_at = NOW()
                RETURNING *;
            """
            result = await self.db_pool.fetchrow(
                query, role_id, role_title, requirements_text, str(embedding), embedding_model
            )
            return dict(result) if result else record

        # Fallback / In-Memory persistence
        key = f"{role_id}::{embedding_model}"
        self._role_vectors[key] = record
        return record

    async def get_student_vector(self, student_id: str, embedding_model: str = EMBEDDING_MODEL_NAME) -> Optional[Dict[str, Any]]:
        """Fetch student vector strictly matching the requested embedding_model."""
        if self.db_pool:
            query = """
                SELECT * FROM public.student_profile_vectors
                WHERE student_id = $1 AND embedding_model = $2;
            """
            row = await self.db_pool.fetchrow(query, student_id, embedding_model)
            return dict(row) if row else None

        key = f"{student_id}::{embedding_model}"
        return self._student_vectors.get(key)

    async def search_matching_roles(
        self,
        query_embedding: List[float],
        query_model: str = EMBEDDING_MODEL_NAME,
        top_k: int = 5
    ) -> List[Dict[str, Any]]:
        """Search role requirements matching query embedding.

        STRICT CONSTRAINT: Only compares vectors created with the EXACT SAME embedding_model.
        Never compares or searches across different embedding_model values.
        """
        if not query_model:
            raise ValueError("Query embedding_model must be specified.")

        if self.db_pool:
            # SQL strictly enforces: WHERE embedding_model = $1
            query = """
                SELECT role_id, role_title, requirements_text, embedding_model,
                       1 - (embedding <=> $2) AS cosine_similarity
                FROM public.role_requirements
                WHERE embedding_model = $1
                ORDER BY embedding <=> $2
                LIMIT $3;
            """
            rows = await self.db_pool.fetch(query, query_model, str(query_embedding), top_k)
            return [dict(r) for r in rows]

        # In-memory cosine similarity strictly matching embedding_model
        matches = []
        for key, role_record in self._role_vectors.items():
            # STRICT MODEL CHECK
            if role_record["embedding_model"] != query_model:
                continue

            # Cosine similarity
            dot = sum(a * b for a, b in zip(query_embedding, role_record["embedding"]))
            norm_a = math.sqrt(sum(a * a for a in query_embedding))
            norm_b = math.sqrt(sum(b * b for b in role_record["embedding"]))
            similarity = dot / (norm_a * norm_b) if norm_a and norm_b else 0.0

            matches.append({
                "role_id": role_record["role_id"],
                "role_title": role_record["role_title"],
                "requirements_text": role_record["requirements_text"],
                "embedding_model": role_record["embedding_model"],
                "cosine_similarity": similarity,
            })

        matches.sort(key=lambda x: x["cosine_similarity"], reverse=True)
        return matches[:top_k]

    def validate_model_compatibility(self, model_a: str, model_b: str) -> None:
        """Helper to assert that two vector models are identical before comparing."""
        if model_a != model_b:
            raise ModelMismatchError(
                f"Cannot compare vectors: model '{model_a}' is incompatible with model '{model_b}'."
            )


# Default global repository instance
vector_repo = VectorRepository()
